# Generated by Django 3.1.2 on 2022-01-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('publish', 'Publish'), ('pending', 'Pending')], default='Pending', max_length=254),
        ),
    ]
