# Generated by Django 3.2.3 on 2022-01-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0006_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
