# Generated by Django 3.2.3 on 2022-01-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0007_post_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='viewers',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
